version: '3'

services:
  wctestapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wctestapp
    restart: unless-stopped
    environment:
      - RELAY_URL=wss://relay.walletconnect.com
    networks:
      - app_network
    # Expose ports for direct access (without proxy)
    # These are not exposed to the host when using Caddy
    expose:
      - "8080"

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app_network
    depends_on:
      - wctestapp

networks:
  app_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: