version: '3'

services:
  wctestapp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_URL=${SERVER_URL:-http://localhost:8080}
      - ENABLE_TLS=${ENABLE_TLS:-false}
      - CERT_FILE=/app/certs/server.crt
      - KEY_FILE=/app/certs/server.key
      - DEBUG=true
    volumes:
      - ./certs:/app/certs
    restart: unless-stopped